Fixes token logging in callbacks when streaming=True is used.
langchain-ai/langchain-aws pull request #241
Opened 2024-10-15 20:03 UTC by 3coins

Fixes #240

2024-10-15 20:16 UTC, 3coins commented
@wuodar @supreetkt
Can you folks verify. Thanks.

2024-10-15 23:04 UTC, supreetkt requested changes

2024-10-15 23:04 UTC, supreetkt commented on libs/aws/langchain_aws/chat_models/bedrock.py
> +                if run_manager:
Adding a check to test for empty/None values will fix the 2 empty responses in the end:
```
 if run_manager and generation_chunk.text:
```

2024-10-15 23:05 UTC, supreetkt commented on libs/aws/langchain_aws/chat_models/bedrock.py
> +                    run_manager.on_llm_new_token(
And the same check should be added here as well.

2024-10-16 14:28 UTC, supreetkt commented
Btw, this check also seems to be missing from SagemakerEndpoint class. So there might be empty tokens there as well.

2024-10-16 17:12 UTC, 3coins commented
@supreetkt 
Thanks for those suggestions. Upon checking some other partner implementations, there doesn't seem to be any filtering of messages in their code based on the content. There are valid cases in which other values in the callbacks might be useful, for example the response_metadata. 

I will look separately into the responses to see if we are yielding extra chunks that shouldn't be exposed. As far as this PR is concerned, I believe this fixes the raised issue. Let me know if you have any other suggestions.

2024-10-16 18:36 UTC, 3coins commented
@supreetkt 

> I checked one partner implementation and they seemed to be checking only to ensure that the output is a string. Here is a sample empty generated chunk

Can you provide a link to that implementation. 

> I can just handle the same logic on my end within our custom implementation of the on_llm_new_token too :)

Yes, I think this can be handled easily by the callbacks based on their use case.

> I had one more concern: I tried using ChatBedrock with beta_use_converse_api set to True and it doesn't stream responses. I think its missing the usage of on_llm_new_token as well.

I will tackle this in a separate PR, but in general `streaming` attribute is legacy and not required at-all, only there for backward compatibility, since streaming is natively supported by LCEL and Runnables, and callbacks approach should be discouraged IMO.

2024-10-16 19:02 UTC, supreetkt commented
Here is the [link](https://github.com/langchain-ai/langchain/blob/a38e9033605ddada70f03b321f94c8e01202bc27/libs/partners/anthropic/langchain_anthropic/chat_models.py#L717)

2024-10-16 19:03 UTC, supreetkt commented
> @supreetkt
> 
> > I checked one partner implementation and they seemed to be checking only to ensure that the output is a string. Here is a sample empty generated chunk
> 
> Can you provide a link to that implementation.
> 
> > I can just handle the same logic on my end within our custom implementation of the on_llm_new_token too :)
> 
> Yes, I think this can be handled easily by the callbacks based on their use case.
> 
> > I had one more concern: I tried using ChatBedrock with beta_use_converse_api set to True and it doesn't stream responses. I think its missing the usage of on_llm_new_token as well.
> 
> I will tackle this in a separate PR, but in general `streaming` attribute is legacy and not required at-all, only there for backwards compatibility, since streaming is natively supported by LCEL and Runnables, and callbacks approach should be discouraged IMO.

Here is the [link](https://github.com/langchain-ai/langchain/blob/a38e9033605ddada70f03b321f94c8e01202bc27/libs/partners/anthropic/langchain_anthropic/chat_models.py#L717)

Also, if you're tackling the converse API issue in a separate PR, this LGTM.

2024-10-17 02:11 UTC, merged