Initial commit of  Amazon Q Business runnable for langchain
langchain-ai/langchain-aws pull request #301
Opened 2024-12-05 18:27 UTC by tomron-aws

2024-12-13 02:15 UTC, michaelnchin requested changes
Thank you for the contribution @tomron-aws ! Added a few comments.

2024-12-17 18:03 UTC, tomron-aws commented on libs/aws/langchain_aws/llms/q_business.py
> +            print(len(prompt))
I've been debating that. Currently Amazon Q ChatSync API only supports a max of 7000 chars. Its helpful to debug in the case that you are passing along additional context with the prompt. 

I think a good place for that log would be in the error handling block, which I added. Let me know what you think

2024-12-17 18:07 UTC, tomron-aws commented on libs/aws/langchain_aws/llms/q_business.py
> +                'applicationId': "130f4ea4-855f-4ddf-b2a5-1e40923692d4",
Removed this code it was leftover from testing

2024-12-17 20:19 UTC, tomron-aws commented on libs/aws/langchain_aws/llms/q_business.py
> +            response = self.client.chat_sync(**request)
I implemented this as well. Let me know if that satisfies the requirements.

2024-12-17 23:06 UTC, michaelnchin commented on libs/aws/langchain_aws/llms/q_business.py
> +            print(len(prompt))
Thanks - let's remove L83/84 in favor of the new changes.

2024-12-17 23:07 UTC, michaelnchin commented on libs/aws/langchain_aws/llms/q_business.py
> +            response = self.client.chat_sync(**request)
Looks good, thanks!

2024-12-17 23:12 UTC, michaelnchin commented on libs/aws/langchain_aws/llms/q_business.py
> +                raise ValueError(f"Error raised by Amazon Q service: {e}")
Remove this line, as it's redundant with L123. Or change the ValueError message here to specifically reference the prompt length constraint

2024-12-23 22:07 UTC, tomron-aws commented
Changed to runnable. Also finished implementing and testing the client validator

2025-01-03 22:48 UTC, michaelnchin requested changes

2025-01-03 22:48 UTC, michaelnchin commented on libs/aws/langchain_aws/runnables/q_business.py
> +        return "amazon_q"
Remove this method for non-LLM class

2025-01-03 22:48 UTC, michaelnchin commented on libs/aws/langchain_aws/runnables/q_business.py
> +    ) -> str:
Replace `_call()` with `invoke()`: 

https://python.langchain.com/api_reference/core/runnables/langchain_core.runnables.base.Runnable.html#langchain_core.runnables.base.Runnable.invoke

2025-01-03 22:48 UTC, michaelnchin commented on libs/aws/langchain_aws/runnables/q_business.py
> +    async def _acall(
Replace `_acall()` with `ainvoke()`: 

https://python.langchain.com/api_reference/core/runnables/langchain_core.runnables.base.Runnable.html#langchain_core.runnables.base.Runnable.ainvoke

2025-01-23 21:50 UTC, 3coins requested changes

2025-01-23 21:50 UTC, 3coins commented on libs/aws/langchain_aws/runnables/q_business.py
> +            return self
```suggestion
```

2025-01-23 21:50 UTC, 3coins commented on libs/aws/langchain_aws/runnables/q_business.py
> +        self.validate_environment()
```suggestion
        self.client = client or self.validate_environment()
```

2025-01-23 21:50 UTC, 3coins commented on libs/aws/langchain_aws/runnables/q_business.py
> +                    self.client = boto3.client('qbusiness', self.region_name, **self.credentials)
```suggestion
                    client = boto3.client('qbusiness', self.region_name, **self.credentials)
```

2025-01-23 21:50 UTC, 3coins commented on libs/aws/langchain_aws/runnables/q_business.py
> +                    self.client = boto3.client('qbusiness', **self.credentials)
```suggestion
                    client = boto3.client('qbusiness', **self.credentials)
```

2025-01-23 21:50 UTC, 3coins commented on libs/aws/langchain_aws/runnables/q_business.py
> +        return self
```suggestion
        return client
```

2025-01-23 21:50 UTC, 3coins commented on libs/aws/langchain_aws/runnables/q_business.py
> +class AmazonQ(Runnable):
```suggestion
from langchain_core._api.beta_decorator import beta

@beta(message="This API is in beta and can change in future.")
class AmazonQ(Runnable[str, str]):
```

2025-01-23 21:50 UTC, 3coins commented on libs/aws/langchain_aws/runnables/q_business.py
> +        )
I believe Runnable defaults to this behavior, so this might be redundant. Can we test after removing this?

2025-01-29 02:10 UTC, michaelnchin commented on libs/aws/langchain_aws/runnables/q_business.py
> +from typing import Any, Dict, Optional
```suggestion
from typing import Any, Dict, Optional, Union
```

2025-01-29 02:10 UTC, michaelnchin commented on libs/aws/langchain_aws/runnables/q_business.py
> +class AmazonQ(Runnable[str, str]):
```suggestion
class AmazonQ(Runnable[Union[str, PromptValue], str]):
```

2025-01-29 02:23 UTC, michaelnchin requested changes

2025-01-29 02:23 UTC, michaelnchin commented on libs/aws/langchain_aws/runnables/q_business.py
> +from typing import Any, Dict, Optional
```suggestion
from typing import Any, Dict, Optional, Union
```

2025-01-29 02:23 UTC, michaelnchin commented on libs/aws/langchain_aws/runnables/q_business.py
> +
```suggestion
from langchain_core.prompt_values import PromptValue
```

2025-01-29 02:23 UTC, michaelnchin commented on libs/aws/langchain_aws/runnables/q_business.py
> +class AmazonQ(Runnable[str, str]):
```suggestion
class AmazonQ(Runnable[Union[str, PromptValue], str]):
```

2025-01-29 02:23 UTC, michaelnchin commented on libs/aws/langchain_aws/runnables/q_business.py
> +        input: Any,
```suggestion
        input: Union[str, PromptValue],
```

2025-01-29 02:23 UTC, michaelnchin commented on libs/aws/langchain_aws/runnables/q_business.py
> +    def convert_langchain_messages_to_q_input(self, input: Any) -> str:
```suggestion
    def convert_langchain_messages_to_q_input(self, input: Union[str, PromptValue]) -> str:
```

2025-01-29 02:23 UTC, michaelnchin commented on libs/aws/langchain_aws/runnables/q_business.py
> +        return "\n".join(messagesToStringArray)
PromptValue has a `to_string()` method that could possibly replace this entire block: https://python.langchain.com/api_reference/core/prompt_values/langchain_core.prompt_values.PromptValue.html#langchain_core.prompt_values.PromptValue

But test it out and ensure that the value returned is still returned in the desired format.

2025-01-29 02:23 UTC, michaelnchin commented on libs/aws/langchain_aws/runnables/q_business.py
> +    def convert_langchain_messages_to_q_input(self, input: Any) -> str:
Add a conditional in this function to check for and immediately return string type inputs.

2025-02-04 20:09 UTC, tomron-aws commented on libs/aws/langchain_aws/runnables/q_business.py
> +    def convert_langchain_messages_to_q_input(self, input: Any) -> str:
Implemented but used the union operator and "ChatPromptValue" which is what is the type being passed form langchain invocation

2025-02-04 20:10 UTC, tomron-aws commented on libs/aws/langchain_aws/runnables/q_business.py
> +    def convert_langchain_messages_to_q_input(self, input: Any) -> str:
Implemented

2025-02-04 21:23 UTC, michaelnchin approved these changes
@tomron-aws confirmed that they have tested the latest changes - LGTM, thanks!

@3coins to provide final review.

2025-02-14 21:08 UTC, KBB99 commented
@3coins any updates on this?

2025-02-25 18:35 UTC, 3coins commented on libs/aws/langchain_aws/runnables/q_business.py
> +class AmazonQ(Runnable[Union[str,ChatPromptValue], str]):
```suggestion
class AmazonQ(Runnable[Union[str, BaseMessage], BaseMessage]):
```

2025-02-25 18:35 UTC, 3coins commented on libs/aws/langchain_aws/runnables/q_business.py
> +        input: Union[str,ChatPromptValue],
```suggestion
        input: Union[str, BaseMessage],
```

2025-02-25 18:36 UTC, 3coins commented on libs/aws/langchain_aws/runnables/q_business.py
> +    ) -> str:
```suggestion
    ) -> BaseMessage:
```

2025-02-25 19:06 UTC, tomron-aws commented on libs/aws/langchain_aws/runnables/q_business.py
> +        input: Union[str,ChatPromptValue],
Implemented and tested succesfully

2025-02-25 20:37 UTC, michaelnchin approved these changes

2025-02-25 21:46 UTC, 3coins commented on libs/aws/langchain_aws/runnables/q_business.py
> +                'userMessage': self.convert_langchain_messages_to_q_input(input), # Langchain's input comes in the form of an array of "messages". We must convert to a single string for Amazon Q's us
@tomron-aws 
I missed your comment here, in your testing of this, does the input come as List of messages or single message when you use it in an App? If that's the case, might want to reflect that in the input type.

```python
Union[str, BaseMessage, List[BaseMessage]]
```

2025-02-25 21:51 UTC, 3coins commented on libs/aws/langchain_aws/runnables/q_business.py
> +        return input.to_string()
See my comment above, if using a list of messages, would each of those need conversion?

2025-02-25 21:53 UTC, 3coins commented on libs/aws/langchain_aws/runnables/q_business.py
> +                return response["systemMessage"]
Shouldn't this be converted into a `AIMessage`?

2025-02-25 21:54 UTC, 3coins commented on libs/aws/langchain_aws/runnables/q_business.py
> +                {input}""")
Is this really needed. Would the exception itself have this info?

2025-02-25 21:56 UTC, 3coins commented on libs/aws/langchain_aws/runnables/q_business.py
> +    def get_last_response(self) -> Dict:
Not clear how `_last_response` is useful. Also, should this be a property?

```suggestion
    @property
    def last_response(self) -> Dict:
```

2025-02-25 23:05 UTC, tomron-aws commented on libs/aws/langchain_aws/runnables/q_business.py
> +                return response["systemMessage"]
Amazon Q returns the AI response as "systemMessage" ([link](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/qbusiness/client/chat_sync.html#:~:text=RETURNS%3A-,Response%20Syntax,-%7B%0A%20%20%20%20%27conversationId%27))

2025-02-25 23:08 UTC, tomron-aws commented on libs/aws/langchain_aws/runnables/q_business.py
> +                {input}""")
It doesn't have the info it just says the hard limit was breached. It's helpful for debugging because developers will need to manage the length of the chain.

2025-02-25 23:08 UTC, tomron-aws commented on libs/aws/langchain_aws/runnables/q_business.py
> +                {input}""")
I can take this out though if it doesn't seem important. This debugging could be done on the client side

2025-02-25 23:12 UTC, tomron-aws commented on libs/aws/langchain_aws/runnables/q_business.py
> +    def get_last_response(self) -> Dict:
It is used to retrieve the reference the response details besides the message. For example, a developer may want to re-use the conversationId or pass the parentMessageId to the next request to keep the same conversation going. So they would need to get this information. ([link](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/qbusiness/client/chat_sync.html#:~:text=parentMessageId%20(string)%20%E2%80%93%20The%20identifier%20of%20the%20previous%20system%20message%20in%20a%20conversation.))

We want it to be easy for developers to invoke the runnable and return a string response containing the AI message. 
But if they have an edge use case where they need other information this is stored so they can retrieve that as well.

2025-02-25 23:16 UTC, tomron-aws commented on libs/aws/langchain_aws/runnables/q_business.py
> +                return response["systemMessage"]
Or are you saying it should be converted to an [AIMessage](https://python.langchain.com/api_reference/core/messages/langchain_core.messages.ai.AIMessage.html) type

2025-02-25 23:21 UTC, tomron-aws commented on libs/aws/langchain_aws/runnables/q_business.py
> +                'userMessage': self.convert_langchain_messages_to_q_input(input), # Langchain's input comes in the form of an array of "messages". We must convert to a single string for Amazon Q's us
This is the type of the input returned from the type function:
`<class 'langchain_core.prompt_values.ChatPromptValue'>`

2025-02-26 15:20 UTC, 3coins commented on libs/aws/langchain_aws/runnables/q_business.py
> +                return response["systemMessage"]
Correct. And AIMessage has `response_metadata` to store additional data that you are currently storing with `_last_response`. Let me know if that will work.

2025-02-26 15:36 UTC, 3coins commented on libs/aws/langchain_aws/runnables/q_business.py
> +                'userMessage': self.convert_langchain_messages_to_q_input(input), # Langchain's input comes in the form of an array of "messages". We must convert to a single string for Amazon Q's us
Right, if we are trying to make this compatible with ChatModels, then [LanguageModelInput](https://github.com/langchain-ai/langchain/blob/master/libs/core/langchain_core/language_models/base.py#L83) is the way to go. But this requires processing the input, like in ChatModel here.
https://github.com/langchain-ai/langchain/blob/9cd20080fc259a84ed326fa492edffc2ca063d22/libs/core/langchain_core/language_models/chat_models.py#L259

We can start with ChatPromptValue for now, if that's the intended use, and then expand to LanguageModelInput later on, will leave that up-to you, but let's reflect that in the types.

2025-02-26 15:41 UTC, 3coins commented on libs/aws/langchain_aws/runnables/q_business.py
> +                {input}""")
Use debug statements if this is useful. Also move to using a logger instead of root logging.
```python
# Add this at the top after the imports
logger = logging.getLogger(__name__)

# In your code
logger.debug(...)
```

2025-02-26 15:44 UTC, 3coins commented on libs/aws/langchain_aws/runnables/q_business.py
> +    def get_last_response(self) -> Dict:
See my comment about embedding this in AIMessage.

2025-02-27 18:54 UTC, tomron-aws commented on libs/aws/langchain_aws/runnables/q_business.py
> +                {input}""")
Added

2025-02-27 18:54 UTC, tomron-aws commented on libs/aws/langchain_aws/runnables/q_business.py
> +    def get_last_response(self) -> Dict:
implemented

2025-02-27 19:00 UTC, tomron-aws commented on libs/aws/langchain_aws/runnables/q_business.py
> +                'userMessage': self.convert_langchain_messages_to_q_input(input), # Langchain's input comes in the form of an array of "messages". We must convert to a single string for Amazon Q's us
I think this makes sense. I think the intended use now is using ChatPromptValue. To use the language model input I would need to dive deeper and understand the use cases that would require that. For now I reverted back to ChatPromptValue

2025-02-27 19:01 UTC, tomron-aws commented on libs/aws/langchain_aws/runnables/q_business.py
> +        return input.to_string()
Currently it does run through the logic, and it does not adversely affect my existing implementations. I will leave this for now and we can revisit this when we asses other input types such as LanguageModelInput

2025-02-27 19:01 UTC, tomron-aws commented on libs/aws/langchain_aws/runnables/q_business.py
> +                return response["systemMessage"]
Implemented

2025-02-27 21:33 UTC, michaelnchin approved these changes

2025-02-27 21:40 UTC, merged