Support Structured and Multi-Modal Response Types in Bedrock Retriever
langchain-ai/langchain-aws pull request #317
Opened 2024-12-30 19:15 UTC by 000-000-000-000-000

## Purpose
Adds support for structured and multi-modal retrieval by updating the Bedrock retriever response parsing logic

## Detailed Changes
1. Modularize retrieval logic in Bedrock retriever to separate a/ request creation b/ response parsing c/ search result to document conversion
2. Make the retrieval config clearly optional + make it clear that it can be either a dictionary or a Python object
3. Add TEXT, IMAGE, and ROW parsing for search results
4. Introduce broader testing regime to test more cases across all of the different output types

## Testing
1. Added and executed new unit tests
2. Installed and ran manual local tests on a few existing Knowledge Bases

2024-12-31 19:24 UTC, rozerarenu approved these changes

2025-01-27 22:23 UTC, jpfcabral commented
Is it already implemented on new versions of the library? Langgraph is extremely dependent on structured responses

2025-01-27 22:52 UTC, 000-000-000-000-000 commented on libs/aws/langchain_aws/retrievers/bedrock.py
> +    def __get_retrieve_request(self, query: str) -> Dict[str, Any]:
better to make this private vs protected.

2025-01-27 22:52 UTC, 000-000-000-000-000 commented on libs/aws/langchain_aws/retrievers/bedrock.py
> +        results: List[Dict[str, Any]],
better to make this private vs protected.

2025-01-27 22:54 UTC, 000-000-000-000-000 commented on libs/aws/langchain_aws/retrievers/bedrock.py
> +    def __filter_by_score_confidence(self, docs: List[Document]) -> List[Document]:
Single "_" is just a convention that indicates consumers shouldnt use. Double "_" changes name of method so upstream classes in inheritance w/ same attribute name won't collide.

2025-01-27 22:55 UTC, 000-000-000-000-000 commented on libs/aws/langchain_aws/retrievers/bedrock.py
> +    @staticmethod
want to make this clear it is still local to this class and shouldn't be used broadly.

2025-01-30 02:49 UTC, 3coins requested changes

2025-01-30 02:49 UTC, 3coins commented on libs/aws/langchain_aws/retrievers/bedrock.py
> +    def __filter_by_score_confidence(self, docs: List[Document]) -> List[Document]:
> upstream classes in inheritance w/ same attribute name won't collide.

Would this case apply anywhere in this context? In all of LangChain, there is not a single method name with double underscores, can we please follow the same convention.

2025-01-30 02:49 UTC, 3coins commented on libs/aws/langchain_aws/retrievers/bedrock.py
> +    retrieval_config: Union[RetrievalConfig, Dict[str, Any], None] = None
Is this an intended change, does the API accept any key-value pair?

2025-01-30 05:38 UTC, 000-000-000-000-000 commented on libs/aws/langchain_aws/retrievers/bedrock.py
> +    retrieval_config: Union[RetrievalConfig, Dict[str, Any], None] = None
This was already a supported pattern, but was not previously documented. RetrievalConfig, while providing a nice CX is limiting in that it must be updated for every launch. Customers can pass a dictionary instead (as long as it adheres to the proper format) to use any available features on KB / for consistency with API docs.

2025-01-31 20:03 UTC, 3coins commented on libs/aws/langchain_aws/retrievers/bedrock.py
> +    retrieval_config: Union[RetrievalConfig, Dict[str, Any], None] = None
I believe the current models also support adding new values to the inputs (with extra=allow), so it does provide that flexibility as well. Having the models does help static analyzers to catch typos or other errors in the inputs during development, that otherwise will be discovered during runtime.

I noticed that the `guardrailConfiguration` is missing from current implementation, if that's the reason of expanding the type here, we can make the appropriate change here to accommodate the new value rather than expanding the type to dict. Let me know what you think.

2025-01-31 20:52 UTC, 000-000-000-000-000 commented on libs/aws/langchain_aws/retrievers/bedrock.py
> +    retrieval_config: Union[RetrievalConfig, Dict[str, Any], None] = None
yes correct on first one. On second one this change is scoped to response types so won't make those updates here but we can follow up with updates to the RetrievalConfig for other features.

2025-01-31 21:11 UTC, 3coins commented
> Is it already implemented on new versions of the library? Langgraph is extremely dependent on structured responses

@jpfcabral let us know if we missed anything here, I will be merging this later today.

2025-01-31 22:00 UTC, merged