adding bedrock token usage callback handler
langchain-ai/langchain-aws pull request #69
Opened 2024-06-06 18:32 UTC by grvvrmtech

Adding callback function for token usage counting,  consulted openai callback.

Co-authored-by: Gaurav Verma <grvvrm.tech.in@gmail.com>

2025-01-12 23:47 UTC, wolfgangcolsman requested changes

2025-01-12 23:47 UTC, wolfgangcolsman commented on libs/aws/langchain_aws/callbacks/bedrock_callback.py
> +MODEL_COST_PER_1K_INPUT_TOKENS = {
The list of models should be updated.
- Pricing for meta has changed
- New Anthropic models
- New Nova models

2025-01-12 23:47 UTC, wolfgangcolsman commented on libs/aws/langchain_aws/callbacks/bedrock_callback.py
> +    return (prompt_tokens / 1000) * MODEL_COST_PER_1K_INPUT_TOKENS[model_id] + (
For Anthropic and Nova models, tokens for cache reads and writes have a different pricing

2025-01-13 03:33 UTC, wolfgangcolsman commented on libs/aws/langchain_aws/callbacks/bedrock_callback.py
> +    return (prompt_tokens / 1000) * MODEL_COST_PER_1K_INPUT_TOKENS[model_id] + (
I created a new PR that adds callback support to ChatBedrockConverse: https://github.com/langchain-ai/langchain-aws/pull/324

2025-01-30 05:04 UTC, michaelnchin reviewed
@grvvrmtech, thank you for the submission. However, at this time, we are looking to avoid maintaining the hard-coded lists of models and prices on the front-end.

2025-03-14 23:20 UTC, closed without merging